### ISSUE TITLE
ActionBar Compat Library

### ISSUE THREAD

**Issue by mokesmokes** [ricardoalcocer/actionbarclone#3]
At this stage in the game the right thing to do is for Titanium to use the official Android Support Library, and thus enable Action Bars on all Android versions. If anyone from Appcelerator can help out with my pull request it would be great! It's actually not a big change on the Titanium Android core
https://jira.appcelerator.org/browse/TIMOB-15021

**Comment by ricardoalcocer** [comment]
This will be officially supported on 3.3 | https://jira.appcelerator.org/browse/TIMOB-15021, but of course @mokesmokes you already know this because I think it was you who created the Jira ticket :)

**Comment by mokesmokes** [comment]
lol - thus closing this ticket.... tnx :)
